# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-11 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200610_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_counts',
            field=models.BigIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='down_counts',
            field=models.BigIntegerField(default=0, verbose_name='点踩数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_counts',
            field=models.BigIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
