# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-11 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200611_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='site',
            new_name='blog',
        ),
    ]
