# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-11 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200611_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Blog',
            new_name='blog',
        ),
    ]
