# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-12 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_comment_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='评论时间'),
        ),
    ]
